/**
 * Map legend (ground element per cell — every tile has one):
 *   L = land       W = water       G = grass      H = tall grass
 *   @ = player spawn (becomes grass)
 *
 * Overlays (trees, signs) are placed separately in TREE_POSITIONS / interactables.js
 * and stack on top of ground without replacing it.
 *
 * Each row must be the same width (40).
 */

export const MAP_DATA = [
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WLLLLLLLLLLGGGGGGGGGLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLGGHHHHHHHGGLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLGGHHHHHHHHHGGLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLGGHHHHHHHHHHGGLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLGGGGGGGGGGGGGGLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLGGGGGGGGGLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLGGHHHHHHHGGLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLGGHHHHHHHHHGGLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLGGHHHHHHHHHHGGLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLGGGGGGGGGGGGGGLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

export const PLAYER_SPAWN = { x: 20, y: 12 }

/** Tree overlays — ground element underneath is preserved from MAP_DATA. */
export const TREE_POSITIONS = [
  { x: 8, y: 5 },
  { x: 9, y: 5 },
  { x: 10, y: 5 },
  { x: 30, y: 5 },
  { x: 31, y: 5 },
  { x: 32, y: 5 },
  { x: 15, y: 18 },
  { x: 16, y: 18 },
  { x: 17, y: 18 },
  { x: 24, y: 18 },
  { x: 25, y: 18 },
]
